version: '1'
services:
parseserver:
  build: .
  ports:
   - "8080:8080"
  depends_on:
   - db
      
db:
  image: postgres:latest
  container_name: postgres
  ports:
    - "5432"
  environment:
   - POSTGRES_DB=parsedb
   - POSTGRES_PASSWORD=teste123
   - POSTGRES_USER=postgres